<form action="<?= $this->url('valuation.impact') ?>" method="post" id="impactForm">
    <input type="hidden" id="aktiva_id" name="aktiva_id" value="<?= $this->id ?>">
    <h3><small>id:</small> <?= $this->id ?></h3>
    <hr>
    <p>Zde budou informace aktiva</p>
    <hr>
    <h2>4. Hodnocení dopadů (vybráno: <span style="background-color: <?= $colorLevel[$valuation['impact_value']] ?>"><?= $levelName[$valuation['impact_value']] ?></span>)</h2>
    <hr>
    <!-- <p><small>2.4.1 ...</small> HA - Hodnota aktiva ... HA = 3^(Du-1)+3^(In-1)+3^(Do-1)</p>
    <hr>
    <h3><small>2.4.2 ...</small> Du - Hodnocení důvěrnosti aktiva (radio with table)</h3> -->

    <table class="table" width="100%">
        <thead>
            <tr>
                <th class="text-center" style="background-color: gray; color: white;">#</th>
                <th class="text-center" style="background-color: green;" value="1" onclick="javascript:clickedImpact(this)">1</th>
                <th class="text-center" style="background-color: yellow;" value="2" onclick="javascript:clickedImpact(this)">2</th>
                <th class="text-center" style="background-color: orange;" value="3" onclick="javascript:clickedImpact(this)">3</th>
                <th class="text-center" style="background-color: red;" value="4" onclick="javascript:clickedImpact(this)">4</th>
            </tr>
            <tr>
                <th class="text-center" style="background-color: gray; color: white;">Úroveň</th>
                <th class="text-center" style="background-color: green;" value="1" onclick="javascript:clickedImpact(this)">Nízká</th>
                <th class="text-center" style="background-color: yellow;" value="2" onclick="javascript:clickedImpact(this)">Střední</th>
                <th class="text-center" style="background-color: orange;" value="3" onclick="javascript:clickedImpact(this)">Vysoká</th>
                <th class="text-center" style="background-color: red;" value="4" onclick="javascript:clickedImpact(this)">Kritická</th>
            </tr>
        </thead>
        <tbody>

            <?php if (isset($this->assets)) : ?>
                <?php foreach ($this->assets as $values) : ?>
                    <tr>
                        <td class="text-center" style="background-color: gray;color: white;">
                            <?= $values['description'] ?>
                        </td>
                        <td class="text-center" value="1" onclick="javascript:clickedImpact(this)" value="1">
                            <?= $values['description_level_1'] ?>
                        </td>
                        <td class="text-center" value="2" onclick="javascript:clickedImpact(this)" value="2">
                            <?= $values['description_level_2'] ?>
                        </td>
                        <td class="text-center" value="3" onclick="javascript:clickedImpact(this)" value="3">
                            <?= $values['description_level_3'] ?>
                        </td>
                        <td class="text-center" value="4" onclick="javascript:clickedImpact(this)" value="4">
                            <?= $values['description_level_4'] ?>
                        </td>
                    </tr>
                <?php endforeach; ?>
            <?php endif; ?>
            <tr>
                <td></td>
                <td class="text-center" value="1" onclick="javascript:clickedImpact(this)">
                    <div class="radio">
                        <input type="radio" id='Impact_1' name="setImpact" value="1" <?php if ($valuation['impact_value'] == '1') : ?> checked <?php endif; ?>>
                    </div>
                </td>
                <td class="text-center" value="2" onclick="javascript:clickedImpact(this)">
                    <div class="radio">
                        <input type="radio" id='Impact_2' name="setImpact" value="2" <?php if ($valuation['impact_value'] == '2') : ?> checked <?php endif; ?>>
                    </div>
                </td>
                <td class="text-center" value="3" onclick="javascript:clickedImpact(this)">
                    <div class="radio">
                        <input type="radio" id='Impact_3' name="setImpact" value="3" <?php if ($valuation['impact_value'] == '3') : ?> checked <?php endif; ?>>
                    </div>
                </td>
                <td class="text-center" value="4" onclick="javascript:clickedImpact(this)">
                    <div class="radio">
                        <input type="radio" id='Impact_4' name="setImpact" value="4" <?php if ($valuation['impact_value'] == '4') : ?> checked <?php endif; ?>>
                    </div>
                </td>
            </tr>
        </tbody>
    </table>
    <hr>
    <div class="row">
        <div class="col-md-4 text-center"><a
                href="<?= $this->url('valuation.availability', ['id' => $valuation['aktiva_id']]) ?>"
                class="btn btn-sm btn-primary">Předchozí (hodnocení dostupnosti)</a></div>
        <div class="col-md-4 text-center">
            <!-- <input type="submit" class="btn btn-success" name="integrity" value="Potvrdit" /> -->
        </div>
        <div class="col-md-4 text-center">
            <?php if (!empty($valuation['impact_value'])) : ?>
                <a href="<?= $this->url('valuation.vulnerability', ['id' => $valuation['aktiva_id']]) ?>" class="btn btn-sm btn-primary">Další (hodnocení zranitelností)</a>
            <?php endif; ?>
        </div>