<form action="<?=$this->url('valuation.integrity')?>" method="post" id="integrityForm">
    <input type="hidden" id="aktiva_id" name="aktiva_id" value="<?= $this->id ?>">
    <h3><small>id:</small> <?= $this->id ?></h3>
    <hr>
    <p>Zde budou informace aktiva</p>
    <hr>
    <h2>2. Hodnocení integrity aktiva (vybráno: <span style="background-color: <?= $colorLevel[$valuation['integrity_value']] ?>"><?=$levelName[$valuation['integrity_value']]?></span>)</h2>
    <hr>
    <table class="table" width="100%">
        <tbody>
            <tr>
                <?php if (isset($this->assets)) : ?>
                    <?php foreach ($this->assets as $values) : ?>
                        <td class="text-center du_level_<?= $values['id'] ?>" style="background-color: <?= $colorLevel[$values['level']] ?>;" value="<?= $values['id'] ?>">
                            <h3><?= $levelName[$values['level']] ?></h3>
                        </td>
                    <?php endforeach; ?>
                <?php endif; ?>
            </tr>
            <tr>
                <?php if (isset($this->description)) : ?>
                    <?php foreach ($this->description as $values) : ?>
                        <td value="<?= $values['id'] ?>">
                            <p><?= $values['description'] ?></p>
                        </td>
                    <?php endforeach; ?>
                <?php endif; ?>
            </tr>
            <tr>
                <?php if (isset($this->radio)) : ?>
                    <?php foreach ($this->radio as $values) : ?>
                        <td class="text-center" value="<?= $values['value'] ?>" onclick="javascript:clickedIntegrity(this)">
                            <div class="radio">
                                <input type="radio" id="Integrity_<?= $values['id'] ?>" name="setIntegrity" value="<?= $values['id'] ?>"
                                <?php if($values['id']== $valuation['integrity_value']):?>
                                    checked
                                <?php endif; ?>>
                            </div>
                        </td>
                    <?php endforeach; ?>
                <?php endif; ?>
            </tr>
        </tbody>
    </table>
<hr>
<div class="row">
    <div class="col-md-4 text-center"><a href="<?=$this->url('valuation.confidentiality',['id'=>$valuation['aktiva_id']])?>"
            class="btn btn-sm btn-primary">Předchozí (hodnocení důvěrnosti)</a></div>
    <div class="col-md-4 text-center">
    &nbsp;
        <!-- <input type="submit" class="btn btn-success" name="confidentiality" value="Potvrdit" /> -->
    </div>
    <div class="col-md-4 text-center">
        <?php if(!empty($valuation['integrity_value'])):?>
        <a href="<?=$this->url('valuation.availability',['id'=>$valuation['aktiva_id']])?>" class="btn btn-sm btn-primary">Další
            (hodnocení dostupnosti)</a>
        <?php endif;?>
    </div>
</div>

</form>