<table>
    <thead>
        <tr>
            <th>Důvěrnost</th>
            <th>Integrita</th>
            <th>Dostupnost</th>
            <th>Dopad</th>
            <th></th>
        </tr>
    </thead>
</table>

<form action="<?=$this->url('valuation.threat')?>" method="post" id="ThreatForm">
    <input type="hidden" id="aktiva_id" name="aktiva_id" value="<?= $this->id ?>">
    <h3><small>id:</small> <?= $this->id ?></h3>
    <hr>
    <p>Zde budou informace aktiva</p>
    <hr>
    <h2>6. Hodnocení hrozeb (vybráno: <span style="background-color: <?=$colorLevel[$valuation['threat_value']]?>">
            <?=$levelName[$valuation['threat_value']]?>
        </span>)</h2>
    <hr>
    <table class="table" width="100%">
        <tbody>
            <tr>
                <?php if (isset($this->assets)) : ?>
                    <?php foreach ($this->assets as $values) : ?>
                        <td class="text-center du_level_<?= $values['id'] ?>" style="background-color: <?=$colorLevel[$values['level']] ?>"
                            value="<?= $values['id'] ?>" onclick="javascript:clickedThreat(this)">
                            <h3><?= $levelName[$values['level']] ?></h3>
                        </td>
                    <?php endforeach; ?>
                <?php endif; ?>
            </tr>
            <tr>
                <?php if (isset($this->description)) : ?>
                    <?php foreach ($this->description as $values) : ?>
                        <td value="<?= $values['id'] ?>" onclick="javascript:clickedThreat(this)">
                            <p><?= $values['description'] ?></p>
                        </td>
                    <?php endforeach; ?>
                <?php endif; ?>
            </tr>
            <tr>
                <?php if (isset($this->radio)) : ?>
                    <?php foreach ($this->radio as $values) : ?>
                        <td class="text-center" value="<?= $values['value'] ?>" onclick="javascript:clickedThreat(this)">
                            <div class="radio">
                                <input type="radio" id="Threat_<?= $values['id'] ?>" name="setThreat" value="<?= $values['id'] ?>"
                                <?php if($values['id'] == $valuation['threat_value']):?>
                                    checked
                                <?php endif; ?>
                                >
                            </div>
                        </td>
                    <?php endforeach; ?>
                <?php endif; ?>
            </tr>
        </tbody>
    </table>
<hr>
<div class="row">
    <div class="col-md-4 text-left"><a href="<?=$this->url('valuation.vulnerability',['id'=>$valuation['aktiva_id']])?>" class="btn btn-sm btn-primary">Předchozí (hodnocení zranitelnosti)</a></div>
    <div class="col-md-4 text-center">
        <!-- <input type="submit" class="btn btn-success" name="vulnerability" value="Potvrdit" /> -->
    </div>
    <div class="col-md-4 text-right">
        <!-- <input type="submit" class="btn btn-danger" name="complete_evaluation" value="Dokončit přepočet" /> -->
    </div>
</div>

</form>