<div class="table-responsive">

    <style>
        .dropdown-menu {
            padding: 0 0 !important;
            margin: 0 0 0 !important;
        }
    </style>

    <h1>Exist valuation aktiva</h1>

    <p id="demo"></p>

    <table class="table table-striped table-sm">

        <thead>

            <tr>
                <th>#</th>
                <th>Aktiva ID</th>
                <th>Důvěrnost</th>
                <th>Integrita</th>
                <th>Dostupnost</th>
                <th>Hodnota aktiva</th>
                <th>Dopad</th>
                <th>Zranitelnost</th>
                <th>Hrozby</th>
                <th>Výsledek</th>
                <th>Akce</th>
            </tr>

        </thead>

        <tbody>
            <?php if (isset($this->echo)) : ?>
            <?php foreach ($this->echo as $valuation) : ?>
            <tr>
                <td>
                    <?= $valuation['id'] ?>
                </td>
                <td>
                    <?= $valuation['aktiva_id'] ?>
                </td>
                <td>
                    <button id="btnGroupDrop_<?= $valuation['aktiva_id'] ?>" type="button" class="btn btn-sm btn-secondary dropdown-toggle"
                        <?php if (!empty($valuation['confidentiality_value'])) : ?> style="background-color:
                        <?= $colorLevel[$valuation['confidentiality_value']] ?>;"
                        <?php endif; ?> data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <?php if (empty($valuation['confidentiality_value'])) : ?>
                        Hodnotit
                        <?php else : ?>
                        <?= $levelName[$valuation['confidentiality_value']] ?>
                        <?php endif; ?>
                    </button>

                    <div class="dropdown-menu" aria-labelledby="btnGroupDrop_<?= $valuation['aktiva_id'] ?>" id="setConfidentiality">

                        <button class="dropdown-item" style="background-color: green;"
                            aria-labelledby="btnGroupDrop_<?= $valuation['aktiva_id'] ?>" data-toggle="tooltip"
                            data-placement="top" title="Zde by byl text hodnocení bla bla bla bla"
                            aktiva_id="<?= $valuation['aktiva_id'] ?>" value="1"
                            onclick="setConfidentiality(this)">Nízké</button>
                        <button class="dropdown-item" style="background-color: yellow;"
                            aria-labelledby="btnGroupDrop_<?= $valuation['aktiva_id'] ?>" data-toggle="tooltip"
                            data-placement="top" title="Zde by byl text hodnocení bla bla bla bla"
                            aktiva_id="<?= $valuation['aktiva_id'] ?>" value="2"
                            onclick="setConfidentiality(this)">Střední</button>
                        <button class="dropdown-item" style="background-color: orange;"
                            aria-labelledby="btnGroupDrop_<?= $valuation['aktiva_id'] ?>" data-toggle="tooltip"
                            data-placement="top" title="Zde by byl text hodnocení bla bla bla bla"
                            aktiva_id="<?= $valuation['aktiva_id'] ?>" value="3"
                            onclick="setConfidentiality(this)">Vysoká</button>
                        <button class="dropdown-item" style="background-color: red;"
                            aria-labelledby="btnGroupDrop_<?= $valuation['aktiva_id'] ?>" data-toggle="tooltip"
                            data-placement="top" title="Zde by byl text hodnocení bla bla bla bla"
                            aktiva_id="<?= $valuation['aktiva_id'] ?>" value="4"
                            onclick="setConfidentiality(this)">Kritická</button>
                    </div>

                </td>
                <td>
                    <button id="btnGroupDrop_<?= $valuation['aktiva_id'] ?>" type="button" class="btn btn-sm btn-secondary dropdown-toggle"
                        <?php if (!empty($valuation['integrity_value'])) : ?> style="background-color:
                        <?= $colorLevel[$valuation['integrity_value']] ?>;"
                        <?php endif; ?> data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <?php if (empty($valuation['integrity_value'])) : ?>
                        Hodnotit
                        <?php else : ?>
                        <?= $levelName[$valuation['integrity_value']] ?>
                        <?php endif; ?>
                    </button>


                    <div class="dropdown-menu" aria-labelledby="btnGroupDrop_<?= $valuation['aktiva_id'] ?>" id="setIntegrity">

                        <button class="dropdown-item" style="background-color: green;"
                            aria-labelledby="btnGroupDrop_<?= $valuation['aktiva_id'] ?>" data-toggle="tooltip"
                            data-placement="top" title="Zde by byl text hodnocení bla bla bla bla"
                            aktiva_id="<?= $valuation['aktiva_id'] ?>" value="1"
                            onclick="setIntegrity(this)">Nízké</button>
                        <button class="dropdown-item" style="background-color: yellow;"
                            aria-labelledby="btnGroupDrop_<?= $valuation['aktiva_id'] ?>" data-toggle="tooltip"
                            data-placement="top" title="Zde by byl text hodnocení bla bla bla bla"
                            aktiva_id="<?= $valuation['aktiva_id'] ?>" value="2"
                            onclick="setIntegrity(this)">Střední</button>
                        <button class="dropdown-item" style="background-color: orange;"
                            aria-labelledby="btnGroupDrop_<?= $valuation['aktiva_id'] ?>" data-toggle="tooltip"
                            data-placement="top" title="Zde by byl text hodnocení bla bla bla bla"
                            aktiva_id="<?= $valuation['aktiva_id'] ?>" value="3"
                            onclick="setIntegrity(this)">Vysoká</button>
                        <button class="dropdown-item" style="background-color: red;"
                            aria-labelledby="btnGroupDrop_<?= $valuation['aktiva_id'] ?>" data-toggle="tooltip"
                            data-placement="top" title="Zde by byl text hodnocení bla bla bla bla"
                            aktiva_id="<?= $valuation['aktiva_id'] ?>" value="4"
                            onclick="setIntegrity(this)">Kritická</button>
                    </div>
                </td>
                <td>
                    <button id="btnGroupDrop_<?= $valuation['aktiva_id'] ?>" type="button" class="btn btn-sm btn-secondary dropdown-toggle"
                        <?php if (!empty($valuation['availability_value'])) : ?> style="background-color:
                        <?= $colorLevel[$valuation['availability_value']] ?>;"
                        <?php endif; ?> data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <?php if (empty($valuation['availability_value'])) : ?>
                        Hodnotit
                        <?php else : ?>
                        <?= $levelName[$valuation['availability_value']] ?>
                        <?php endif; ?>
                    </button>


                    <div class="dropdown-menu" aria-labelledby="btnGroupDrop_<?= $valuation['aktiva_id'] ?>" id="setAvailability">
                        <button class="dropdown-item" style="background-color: green;"
                            aria-labelledby="btnGroupDrop_<?= $valuation['aktiva_id'] ?>" data-toggle="tooltip"
                            data-placement="top" title="Zde by byl text hodnocení bla bla bla bla"
                            aktiva_id="<?= $valuation['aktiva_id'] ?>" value="1"
                            onclick="setAvailability(this)">Nízké</button>
                        <button class="dropdown-item" style="background-color: yellow;"
                            aria-labelledby="btnGroupDrop_<?= $valuation['aktiva_id'] ?>" data-toggle="tooltip"
                            data-placement="top" title="Zde by byl text hodnocení bla bla bla bla"
                            aktiva_id="<?= $valuation['aktiva_id'] ?>" value="2"
                            onclick="setAvailability(this)">Střední</button>
                        <button class="dropdown-item" style="background-color: orange;"
                            aria-labelledby="btnGroupDrop_<?= $valuation['aktiva_id'] ?>" data-toggle="tooltip"
                            data-placement="top" title="Zde by byl text hodnocení bla bla bla bla"
                            aktiva_id="<?= $valuation['aktiva_id'] ?>" value="3"
                            onclick="setAvailability(this)">Vysoká</button>
                        <button class="dropdown-item" style="background-color: red;"
                            aria-labelledby="btnGroupDrop_<?= $valuation['aktiva_id'] ?>" data-toggle="tooltip"
                            data-placement="top" title="Zde by byl text hodnocení bla bla bla bla"
                            aktiva_id="<?= $valuation['aktiva_id'] ?>" value="4"
                            onclick="setAvailability(this)">Kritická</button>
                    </div>
                </td>
                <td class="text-center">
                    <?= $valuation['asset_value'] ?>
                </td>
                <td>
                    <button id="btnGroupDrop_<?= $valuation['aktiva_id'] ?>" type="button" class="btn btn-sm btn-secondary dropdown-toggle"
                        <?php if (!empty($valuation['impact_value'])) : ?>
                        style="background-color:
                        <?= $colorLevel[$valuation['impact_value']] ?>;"
                        <?php endif; ?> data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <?php if (empty($valuation['impact_value'])) : ?>
                        Hodnotit
                        <?php else : ?>
                        <?= $levelName[$valuation['impact_value']] ?>
                        <?php endif; ?>
                    </button>
                    
                    
                    <div class="dropdown-menu" aria-labelledby="btnGroupDrop_<?= $valuation['aktiva_id'] ?>" id="setImpact">
                    
                        <button class="dropdown-item" style="background-color: green;"
                            aria-labelledby="btnGroupDrop_<?= $valuation['aktiva_id'] ?>" data-toggle="tooltip" data-placement="top"
                            title="Zde by byl text hodnocení bla bla bla bla" aktiva_id="<?= $valuation['aktiva_id'] ?>" value="1"
                            onclick="setImpact(this)">Nízké</button>
                        <button class="dropdown-item" style="background-color: yellow;"
                            aria-labelledby="btnGroupDrop_<?= $valuation['aktiva_id'] ?>" data-toggle="tooltip" data-placement="top"
                            title="Zde by byl text hodnocení bla bla bla bla" aktiva_id="<?= $valuation['aktiva_id'] ?>" value="2"
                            onclick="setImpact(this)">Střední</button>
                        <button class="dropdown-item" style="background-color: orange;"
                            aria-labelledby="btnGroupDrop_<?= $valuation['aktiva_id'] ?>" data-toggle="tooltip" data-placement="top"
                            title="Zde by byl text hodnocení bla bla bla bla" aktiva_id="<?= $valuation['aktiva_id'] ?>" value="3"
                            onclick="setImpact(this)">Vysoká</button>
                        <button class="dropdown-item" style="background-color: red;"
                            aria-labelledby="btnGroupDrop_<?= $valuation['aktiva_id'] ?>" data-toggle="tooltip" data-placement="top"
                            title="Zde by byl text hodnocení bla bla bla bla" aktiva_id="<?= $valuation['aktiva_id'] ?>" value="4"
                            onclick="setImpact(this)">Kritická</button>
                    </div>
                </td>
                <td>
                    <button id="btnGroupDrop_<?= $valuation['aktiva_id'] ?>" type="button" class="btn btn-sm btn-secondary dropdown-toggle"
                        <?php if (!empty($valuation['vulnerability_value'])) : ?> style="background-color:
                        <?= $colorLevel[$valuation['vulnerability_value']] ?>;"
                        <?php endif; ?> data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <?php if (empty($valuation['vulnerability_value'])) : ?>
                        Hodnotit
                        <?php else : ?>
                        <?= $levelName[$valuation['vulnerability_value']] ?>
                        <?php endif; ?>
                    </button>
                    
                    
                    <div class="dropdown-menu" aria-labelledby="btnGroupDrop_<?= $valuation['aktiva_id'] ?>" id="setVulnerability">
                    
                        <button class="dropdown-item" style="background-color: green;"
                            aria-labelledby="btnGroupDrop_<?= $valuation['aktiva_id'] ?>" data-toggle="tooltip" data-placement="top"
                            title="Zde by byl text hodnocení bla bla bla bla" aktiva_id="<?= $valuation['aktiva_id'] ?>" value="1"
                            onclick="setVulnerability(this)">Nízké</button>
                        <button class="dropdown-item" style="background-color: yellow;"
                            aria-labelledby="btnGroupDrop_<?= $valuation['aktiva_id'] ?>" data-toggle="tooltip" data-placement="top"
                            title="Zde by byl text hodnocení bla bla bla bla" aktiva_id="<?= $valuation['aktiva_id'] ?>" value="2"
                            onclick="setVulnerability(this)">Střední</button>
                        <button class="dropdown-item" style="background-color: orange;"
                            aria-labelledby="btnGroupDrop_<?= $valuation['aktiva_id'] ?>" data-toggle="tooltip" data-placement="top"
                            title="Zde by byl text hodnocení bla bla bla bla" aktiva_id="<?= $valuation['aktiva_id'] ?>" value="3"
                            onclick="setVulnerability(this)">Vysoká</button>
                        <button class="dropdown-item" style="background-color: red;"
                            aria-labelledby="btnGroupDrop_<?= $valuation['aktiva_id'] ?>" data-toggle="tooltip" data-placement="top"
                            title="Zde by byl text hodnocení bla bla bla bla" aktiva_id="<?= $valuation['aktiva_id'] ?>" value="4"
                            onclick="setVulnerability(this)">Kritická</button>
                    </div>
                </td>
                <td>
                    <button id="btnGroupDrop_<?= $valuation['aktiva_id'] ?>" type="button" class="btn btn-sm btn-secondary dropdown-toggle"
                        <?php if (!empty($valuation['threat_value'])) : ?> style="background-color:
                        <?= $colorLevel[$valuation['threat_value']] ?>;"
                        <?php endif; ?> data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <?php if (empty($valuation['threat_value'])) : ?>
                        Hodnotit
                        <?php else : ?>
                        <?= $levelName[$valuation['threat_value']] ?>
                        <?php endif; ?>
                    </button>
                    
                    
                    <div class="dropdown-menu" aria-labelledby="btnGroupDrop_<?= $valuation['aktiva_id'] ?>" id="setThreat">
                    
                        <button class="dropdown-item" style="background-color: green;"
                            aria-labelledby="btnGroupDrop_<?= $valuation['aktiva_id'] ?>" data-toggle="tooltip" data-placement="top"
                            title="Zde by byl text hodnocení bla bla bla bla" aktiva_id="<?= $valuation['aktiva_id'] ?>" value="1"
                            onclick="setThreat(this)">Nízké</button>
                        <button class="dropdown-item" style="background-color: yellow;"
                            aria-labelledby="btnGroupDrop_<?= $valuation['aktiva_id'] ?>" data-toggle="tooltip" data-placement="top"
                            title="Zde by byl text hodnocení bla bla bla bla" aktiva_id="<?= $valuation['aktiva_id'] ?>" value="2"
                            onclick="setThreat(this)">Střední</button>
                        <button class="dropdown-item" style="background-color: orange;"
                            aria-labelledby="btnGroupDrop_<?= $valuation['aktiva_id'] ?>" data-toggle="tooltip" data-placement="top"
                            title="Zde by byl text hodnocení bla bla bla bla" aktiva_id="<?= $valuation['aktiva_id'] ?>" value="3"
                            onclick="setThreat(this)">Vysoká</button>
                        <button class="dropdown-item" style="background-color: red;"
                            aria-labelledby="btnGroupDrop_<?= $valuation['aktiva_id'] ?>" data-toggle="tooltip" data-placement="top"
                            title="Zde by byl text hodnocení bla bla bla bla" aktiva_id="<?= $valuation['aktiva_id'] ?>" value="4"
                            onclick="setThreat(this)">Kritická</button>
                    </div>
                </td>
                <td>
                    <?= $valuation['result_of_degree_of_risk'] ?>
                </td>
                <td>
                    <!-- Button trigger modal -->
                    <button type="button" class="btn btn-sm btn-primary" data-toggle="modal"
                        onclick="getValueModal(<?=$valuation['aktiva_id']?>)">
                        Hodnotit
                    </button>
                    <a href="<?= $this->url('valuation.confidentiality', ['id' => $valuation['aktiva_id']]) ?>"
                        class="btn btn-sm btn-success">Hodnotit</a>
                </td>
                </tr>
                <?php endforeach; ?>
                <?php endif; ?>

        </tbody>

    </table>
</div>



<!-- Modal -->
<div class="modal fade" id="modalValuation" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Hodnocení aktiva</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <input id="aktiva_id" type="hidden">
                <table class="table" width="100%">
                    <thead>
                        <tr>
                            <th style="background-color: gray; color: white;"></th>
                            <th style="background-color: green;">1. Nízká</th>
                            <th style="background-color: yellow;">2. Střední</th>
                            <th style="background-color: orange;">3. Vysoká</th>
                            <th style="background-color: red;">4. Kritická</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr id="modal_">
                            <td style="background-color: lightgray;">Důvernost</td>
                            <td class="text-center"><input type="radio" name="setConfidentiality" value="1" onclick="modalSetValuation(this)"></td>
                            <td class="text-center"><input type="radio" name="setConfidentiality" value="2" onclick="modalSetValuation(this)"></td>
                            <td class="text-center"><input type="radio" name="setConfidentiality" value="3" onclick="modalSetValuation(this)"></td>
                            <td class="text-center"><input type="radio" name="setConfidentiality" value="4" onclick="modalSetValuation(this)"></td>
                        </tr>
                        <tr>
                            <td style="background-color: lightgray;">Integrity</td>
                            <td class="text-center"><input type="radio"></td>
                            <td class="text-center"><input type="radio"></td>
                            <td class="text-center"><input type="radio"></td>
                            <td class="text-center"><input type="radio"></td>
                        </tr>
                        <tr>
                            <td style="background-color: lightgray;">Dostupnost</td>
                            <td class="text-center"><input type="radio"></td>
                            <td class="text-center"><input type="radio"></td>
                            <td class="text-center"><input type="radio"></td>
                            <td class="text-center"><input type="radio"></td>
                        </tr>
                        <tr>
                            <td style="background-color: lightgray;">Dopad</td>
                            <td class="text-center"></td>
                            <td class="text-center"></td>
                            <td class="text-center"></td>
                            <td class="text-center"></td>

                        </tr>
                        <tr>
                            <td style="background-color: lightgray;">Zranitelnost</td>
                            <td class="text-center"></td>
                            <td class="text-center"></td>
                            <td class="text-center"></td>
                            <td class="text-center"></td>
                        </tr>
                        <tr>
                            <td style="background-color: lightgray;">Hrozby</td>
                            <td class="text-center"></td>
                            <td class="text-center"></td>
                            <td class="text-center"></td>
                            <td class="text-center"></td>
                        </tr>
                    </tbody>
                </table>

                <table class="table" width="100%">
                    <thead>
                        <tr>
                            <th class="text-center align-middle">Hodnota activa</th>
                            <th class="text-center align-middle">Výsledná míra rizika</th>
                            <th class="text-center align-middle">Míra rizika</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>
                        <tr>
                            <td colspan="1" class="text-center align-middle"><b>Výsledek<b></td>
                            <td colspan="2"></td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Zavřít</button>
                <!-- <button type="button" class="btn btn-primary">Save changes</button> -->
            </div>
        </div>
    </div>
</div>