version: '3'

services:
  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: mezzio
      MYSQL_USER: stulda
      MYSQL_PASSWORD: 1234
    ports:
      - "8081:3306"

  laminas:
    build: .
    # dockerfile: Dockerfile
    depends_on:
      - database
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
    stdin_open: true
    tty: true
